FROM hyperionng:latest

# Install hyperion from nightly repo
RUN "deb [signed-by=/usr/share/keyrings/hyperion.pub.gpg] https://nightly.apt.releases.hyperion-project.org/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hyperion.list

RUN apt-get update && \
    apt-get install -y hyperion && \
    apt-get clean
